### ISSUE TITLE
`renderpy` generate depth map

### ISSUE THREAD

**Issue by watermelon097** [scannetpp/scannetpp#100]
Hey,

I was checking the code of depth map rendering from `renderpy`
```
        glReadBuffer(GL_COLOR_ATTACHMENT1);
        glPixelStorei(GL_PACK_ALIGNMENT, 1);
        glReadPixels(0, 0, width, height, GL_RED, GL_FLOAT, depth_image.data);
```

why is using `GL_RED` to generate depth? shouldn't use `GL_DEPTH_COMPONENT`?

**Comment by liu115** [comment]
Hello, 

here the depth is a customized frame buffer which has single-channel (GL_RED) and the type is float32 ([defined here](https://github.com/liu115/renderpy/blob/97d337d85fce12dbe6377026aa8fcfb8ef2f9abe/src/opengl/opengl.h#L465-L468)), instead of the default depth buffer used in OpenGL, so we need to read the pixel values from the frame buffer with the same format when we create it. 

The reason to create a additional frame buffer to store depth is because the default depth buffer has a different value range (due to some normalization in OpenGL) that we cannot easily control.

I could also be wrong since I'm not an expert in OpenGL. Did you notice any major error from the depth map in this way? or did it work for you by replacing `GL_RED` with `GL_DEPTH_COMPONENT`?

API: https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glReadPixels.xhtml
Other reference [ETH3D](https://github.com/ETH3D/dataset-pipeline/blob/e09275b39b30c9c59abf535b849fcc539dc03efd/src/opengl/renderer.cc#L845).
