### ISSUE TITLE
Images have different widths when using undisort script

### ISSUE THREAD

**Issue by HannahHaensen** [scannetpp/scannetpp#52]
![image](https://github.com/scannetpp/scannetpp/assets/22636930/2b8e331c-6e72-4ab9-8149-606e63133b11)
![image](https://github.com/scannetpp/scannetpp/assets/22636930/8b7616fa-df3b-4098-a8ed-a9b0d5f4a95f)
![image](https://github.com/scannetpp/scannetpp/assets/22636930/06e1b08e-8471-4b97-81f7-b5132a8a2055)

for example sequence: 1f7cbbdde1 and 419cbe7c11

**Comment by liu115** [comment]
Are you using the opencv undistortion script or the colmap undistortion?

**Comment by HannahHaensen** [comment]
this one: [https://github.com/scannetpp/scannetpp/blob/main/dslr/undistort.py](https://github.com/scannetpp/scannetpp/blob/main/dslr/undistort.py)

**Comment by liu115** [comment]
Can you try the opencv undistortion? It's the official script that is used for NVS benchmark (undisortion track).
https://github.com/scannetpp/scannetpp?tab=readme-ov-file#undistortion-convert-fisheye-images-to-pinhole-with-opencv

We are considering to removing the colmap undistortion script since it has less control.
