### ISSUE TITLE
About the rendered depth & RGB images

### ISSUE THREAD

**Issue by HaoyiZhu** [scannetpp/scannetpp#78]
Hi,

I try to following the instructions to render depth for DSLR using `renderpy`. However, I find that the rendered results are distorted and have a lot of white areas, just like this:
![image](https://github.com/scannetpp/scannetpp/assets/63538191/b002669f-ab86-4c4e-84ef-7fee7098ddae)
![image](https://github.com/scannetpp/scannetpp/assets/63538191/b144fb7b-8200-4852-8223-3e525bb16e26)

Are these expected?

**Comment by HaoyiZhu** [comment]
I know invalid depth values will be set to 0. However, it seems that the while areas are just walls, which I think should not be invalid.

**Comment by HaoyiZhu** [comment]
Also, I find that the dslr RGB images are different with rendered RGB images / mesh colors in terms of lighting conditions, etc.
DSLR:
![DSC07775](https://github.com/scannetpp/scannetpp/assets/63538191/8f668935-7ccf-4e7a-adfc-5f2a2ebd0f6b)
Rendered from mesh:
![DSC07775](https://github.com/scannetpp/scannetpp/assets/63538191/42d56883-35ed-4f4e-8c1d-695db1cfb677)

Why are they inconsistent?

**Comment by liu115** [comment]
Hi @HaoyiZhu! I will try my best to answer your questions in the following.

**Distortion**: It seems like you are working on undistorted images with DSLR. However, the provided rendering code works on the original fisheye DSLR. If you want to render the undistorted depth as well, you can try
1. Apply the similar undistortion code on the output depth (similar to this [issue](https://github.com/scannetpp/scannetpp/issues/65#issuecomment-1939346286))
2. Replace the input camera parameters to renderpy with the undistorted camera parameters. The code would be like
```python
# new_K is the undistorted camera intrinsic matrix
fx = new_K[0, 0]
fy = new_K[1, 1]
cx = new_K[0, 2]
cy = new_K[1, 2]
camera_model = "PINHOLE"
distort_params = np.zeros(4)

render_engine.setupCamera(
    height, width,
    fx, fy, cx, cy,
    camera_model,
    distort_params,
)
``` 


**White areas**: If you can visualize the mesh of the scene, it does not contain all the surroundings. Therefore, the rendered depth and RGB will have empty areas. You could tell by filtering out `depth_map > 0`. Most of our scenes contain complete surroundings (e.g., all the walls) when scanning, so you could also try out other scenes to avoid this issue.

Notice that even complete scenes will have holes in the mesh due to the laser scanning, so I would recommend using `depth_map > 0` as a mask if you're trying something like depth supervision loss or depth evaluation.

**Color**: the behavior is expected. The RGB of the mesh are captured by the camera mounted on the laser scanner, which is independent from our DSLR capture. Therefore, the color will be inconsistent between the two. Just out of curiosity, what types of task are you working on that requires the two RGB to be consistent?

**Comment by HaoyiZhu** [comment]
Thanks for your detailed reply! Actually I do not have to make the two RGB to be consistent, I'm just curious about it :) So, for example, if I want to use DSLR images while also use depth information, I can simply use the rendered depth images as the depth GT of DSLR images, right? Since I assume they should share the same rooms.
