### ISSUE TITLE
Undistortion for iPhone images

### ISSUE THREAD

**Issue by botaoye** [scannetpp/scannetpp#94]
Dear authors, thanks for your great work.

I have found only instructions for distorting a DSLR fisheye image into an OpenCV pinhole camera model. However, I noticed that the iPhone images also have distortion parameters in the COMLAP data, so I'm wondering if it's necessary to distort the iPhone images as well? For example, if I want to train 3DGS using iPhone images, can I ignore the distortion parameters or do I need to distort them first?

**Comment by liu115** [comment]
Good question. Indeed, our colmap of iphone is using the OPENCV camera model which contains distortion parameters. Ideally, the same undistortion script should work with minimal changes, so you can get the undistorted iphone frames if you want. I believe it will also work ignoring the distortion parameters and assuming it's pinhole since the distortion should be minor.  However, I don't have an thorough experiment showing the difference between the two currently on 3DGS.

**Comment by botaoye** [comment]
Got it, thank you for your reply.
